### ISSUE TITLE
Support 2FA `--otp=123456`

### ISSUE THREAD

**Issue by hzoo** [lerna/lerna#1091]
https://docs.npmjs.com/getting-started/using-two-factor-authentication

Need a prompt to be able to pass this for publishing, etc (right before since not that much time)

EDIT: current workaround is `NPM_CONFIG_OTP=123456 lerna publish`

**Comment by evocateur** [comment]
I'm worried that we'll have to re-prompt if publishes start failing (due to expired TOTP). Really exposes how un-tested and gnarly our current publish failure handling is. :/

**Comment by hzoo** [comment]
Yeah that's what happened, also since we published like 100 pkgs and it would expire in between (had to just turn it off)

**Comment by djfarrelly** [comment]
To help people in the short term, perhaps npm's tokens could help. Creating a wrapper script to generate a token, adding it to your `.npmrc` then publishing using lerna then removing and deleting the token could work.

Docs: https://docs.npmjs.com/getting-started/working_with_tokens
Other helpful info: https://circleci.com/docs/1.0/npm-private-module-dependency/

**Comment by rhysforyou** [comment]
For people finding this through Google, I'd like to point out that a good workaround is to set the `NPM_CONFIG_OTP` environment variable before running `lerna publish`, e.g.

```sh
NPM_CONFIG_OTP=123456 lerna publish
```

**Comment by jthegedus** [comment]
The above solution doesn't seem to work with Yarn & lerna as a devDep, eg:

```shell
NPM_CONFIG_OTP=123456 yarn lerna publish
```

It still fails on the OTP during publication :disappointed:

**Comment by jthegedus** [comment]
Fair point. I was under the impression that Yarn read all of npm's configs, wishful thinking. A note for others nonetheless.

**Comment by dupski** [comment]
+1 for lerna to prompt for this, although `NPM_CONFIG_OTP` seems to work ok. Turning off 2FA doesn't seem like a good solution :)

**Comment by rgbkrk** [comment]
As a result of the [recent compromise](https://status.npmjs.org/incidents/dn7c1fgrr7ng), I'd love to be able to enforce 2FA across our org. Is there a way to do the `npm pack` approach with lerna now or does this need work within lerna itself?

**Comment by kachkaev** [comment]
One thing to be aware of is https://github.com/npm/npm/issues/19425. 2FAOTP may timeout during the upload process and thus fail the publish. This is even the case for single npm uploads, so may be also common in lerna context. I'm not say that 2FA should be disabled because of this, just pointing to a related issue is a big pain for me on slow connections.

Perhaps, lerna could check for 401 during publishing and re-ask OTP in this case?

**Comment by hzoo** [comment]
Great point @kachkaev, it's definitely more of an issue with Lerna given multiple packages even if you have a fast connection.

**Comment by iarna** [comment]
Two phase publishes with staging is something we've been talking about. It's a rather substantial platform change, but it is one we intend to see done.

**Comment by loganfsmyth** [comment]
@iarna Cool! I don't doubt that it'd be quite a large change. Thanks to you and everyone at npm for all your hard work :)

**Comment by iarna** [comment]
I was chatting about this with Ceej today and we may have an alternative and _much easier to implement_ solution for you all:

Time-limited tokens. You could create an access token for the purposes of publication that does not require 2fa and is valid for the next 5 or 10 minutes. Then use that during the various publications. 

Creating the token would require 2fa, but using it would not. And it would auto-delete itself after it times out.

**Comment by loganfsmyth** [comment]
That seems like it'd be a great solution.

**Comment by ljharb** [comment]
That seems like a great solution in general, not just for monorepos. @iarna, any possibility of being able to customize longer periods? Like an hour, perhaps?

**Comment by rexxars** [comment]
Created a thread on [npm.community](https://npm.community/t/time-limited-tokens/502) to track/discuss the suggested time-limited token idea outside of this issue.

**Comment by dazlious** [comment]
Any relevant news on this topic?  `NPM_CONFIG_OTP` is not working for us, because we have a lot of packages, which cannot be processed within 30secs

**Comment by iarna** [comment]
I've mentioned this elsewhere (and perhaps it's already been included), but the only thing I'm aware of that lerna can do to improve the situation as things stand today, would be to generate the tarballs first (`npm pack`), and then after they're produced, publish them with `npm publish <tarball name>`. This will at least limit the publication delay to what's happening on the registry, though it probably won't be sufficient to eliminate these issues for users with 100+ modules. The window for publication is actually a bit longer than 30 seconds, but not hugely so.

Time limited tokens _are_ on our list of features we'd like to add to 2fa tokens, both from npm's security team and from my own, but work is not yet scheduled to add them and I'm afraid I don't yet have a timeline for that.

**Comment by evocateur** [comment]
I have implemented the "pack first, publish second" algorithm, but unfortunately you still can't run the two phases separately, passing an up-to-date OTP before the publish phase only.

I have a branch with tentative beginnings, mostly about querying the registry to see if 2FA is required. I haven't gotten around to refactoring the publish loop into an E401-catching, OTP-prompting, restartable queue, however...

**Comment by ThisIsMissEm** [comment]
@evocateur tonight I started working on OTP support, without realising you'd already started working on it (I forgot to check this issue before starting). I've made a few changes:

- Change `npm-publish` to be able to [detect OTP failures for both npm and yarn](https://github.com/lerna/lerna/compare/master...ThisIsMissEm:feat/otp-support#diff-90ed5d25119e69787b824743e893324bR55), with [fixtures](https://github.com/lerna/lerna/compare/master...ThisIsMissEm:feat/otp-support#diff-f30085d2d820ceda2c9020b70a7892e6) and [tests](https://github.com/lerna/lerna/compare/master...ThisIsMissEm:feat/otp-support#diff-2353b7c55ffd1a8364f844893c57ad91R105)
- Change `npm-publish` to [not remove package tarballs](https://github.com/lerna/lerna/compare/master...ThisIsMissEm:feat/otp-support#diff-90ed5d25119e69787b824743e893324bL41), and instead do that as part of [`publish command`](https://github.com/lerna/lerna/compare/master...ThisIsMissEm:feat/otp-support#diff-56ed0a11eeb3e4cc27f62fa99ba32c6aR529) — this gives a clearer separation of concerns.

I think you've definitely the better direction over in your branch, and I'd be happy to collaborate where possible.

**Comment by ThisIsMissEm** [comment]
@evocateur my next step was looking into how the publishes actually work, catching the `PublishError` that I created, and then retrying the batch after requesting a new OTP.

**Comment by ThisIsMissEm** [comment]
@evocateur we could probably wrap the [`mapper`](https://github.com/lerna/lerna/blob/master/commands/publish/index.js#L525) in [pRetry](https://github.com/sindresorhus/p-retry) — using `onFailedAttempt` to catch the `PublishError`, triggering a call to `requestOneTimePassword` (from your branch)

**Comment by gziolo** [comment]
> I have a branch with tentative beginnings, mostly about querying the registry to see if 2FA is required. I haven't gotten around to refactoring the publish loop into an E401-catching, OTP-prompting, restartable queue, however...

At [WordPress](https://github.com/WordPress/gutenberg) we have almost 50 packages maintained with Lerna: https://www.npmjs.com/org/wordpress. It almost impossible to publish more than 15 updated packages with one token. It would be awesome if you could ask to provide the token again when timeout happens. Is there any way we could contribute to this task?

**Comment by ThisIsMissEm** [comment]
Hi Grzegorz,

So far between you, me, and @evocatuer, we've four branches in basically the same state.

I have code that handled issues with the OTP responses from both npm and yarn, but after discussing it further in private, it seemed to not be the way forwards, and that we should instead look to move to libnpmpublish, which would be far more maintainable.

The problem with using a queue where failed packages are retried is that it can then lead to the scenario of an npm install failing because some packages are at a different "latest" than others — this would lead to flakiness in CI systems during publishes.

Have a look at this ticket & see if the approach forwards makes sense to you?

https://github.com/lerna/lerna/issues/1767

It is a major change, but I think it's the best way out of the current complexities that we have in lerna publish.

**Comment by ThisIsMissEm** [comment]
Wow, that was great; the email from github didn't read as if your were quoting me @gziolo

**Comment by ThisIsMissEm** [comment]
@gziolo Have a look at #1767 and see if the approach forwards makes sense to you?

It is a major change, but I think it's the best way out of the current complexities that we have in lerna publish.

**Comment by gziolo** [comment]
@ThisIsMissEm, how nice. Thanks for opening this issue. I will take a closer look tomorrow and open an issue in our repository with the detailed description of what issues we had so far and how we would like to update our workflow to make it easier to maintain. I will re-share in the linked issue. We also plan to discuss this a bit tomorrow during weekly WordPress core JS chat.

**Comment by ntwb** [comment]
FYI: When I was attempting to publish the @wordpress packages with Lerna a couple of days ago I had switched my npmjs.com 2FA profile to `authorization only` mode, fully expecting that supplying a valid npm OTP token at the start of the `lerna publish` command would be sufficient, it wasn't, it still failed to publish the packages due to OTP time out.

Should this have worked? I was logged in, checked by `npom whoami`, should have I logged out and back in again first to allow npm to pick up my new 2FA profile of `authorization only` mode?

**Comment by ThisIsMissEm** [comment]
That'd be due to: https://npm.community/t/2fa-security-skipping-otp-on-npm-publish-when-relogin/3074

**Comment by ntwb** [comment]
Thanks @ThisIsMissEm, the reply on that thread states the issue has been resolved

**Comment by fson** [comment]
I’ve been using the `NPM_CONFIG_OTP` variable, but it fails often because the one time password expires before publishing finishes.

Until full support for npm 2fa has been implemented in Lerna, would it be reasonable to change the options npm/Yarn is spawned with to use `stdio = 'inherit'`? This would allow nom/Yarn to show the normal prompt for OTP when authentication fails due to 2FA. Right now it’s not shown because the commad runs with a non-TTY input stream.

**Comment by ThisIsMissEm** [comment]
We could probably add that as a flag, but changing the default behavior would be a breaking change.

I'd consider this a good stop-gap solution.

**Comment by imaman** [comment]
What's the status of the https://github.com/lerna/lerna/tree/one-time-password-to-rule-them-all branch? I keep doing local patches of it as it is currently the only solution for using lerna with OTP

**Comment by ricmoo** [comment]
Can you point me in the right direction as to which file I need to update/patch to change the studio to "inherit"?

Thanks!! :)

**Comment by evocateur** [comment]
Lerna no longer calls `npm publish` in a subprocess, so that solution is no longer possible.

**Comment by ricmoo** [comment]
I see. That may explain why the export technique isn’t working for me either then?

Is there any existing work around? Even if it involves patching the bin/lerna?

**Comment by ricmoo** [comment]
@imaman Can you share your technique for patching? :)

**Comment by busticated** [comment]
@ricmoo implementation details aside, i've had a ton of success with: https://github.com/ds300/patch-package

**Comment by imaman** [comment]
@ricmoo: there's a branch called "one-time-password-to-rule-them-all" which contains a proposed solution. 



Link to the branch: https://github.com/lerna/lerna/tree/one-time-password-to-rule-them-all

**Comment by ricmoo** [comment]
@busticated Oh, I meant specifically what lines and files to modify for the purpose of OTP w/ Lerna. :)

@imaman Is that safe? I checked it out the other day and it was 114 commits behind... :s

**Comment by imaman** [comment]
@ricmoo: The actual fix is very small so I selectively copied only this part. Unfortunately, I am away from my laptop for the next 10 days so I can't send you a copy-and-paste snippet.

**Comment by ricmoo** [comment]
@imaman No worries, that helps a tonne. I'll copy it over (maybe experiment with a smaller test repo first). :)

**Comment by evocateur** [comment]
Published in [v3.14.0](https://github.com/lerna/lerna/releases/tag/v3.14.0). Used it to publish it, even. ^_^
