### ISSUE TITLE
Latest nx causing "Daemon is not running" error when using "watch"

### ISSUE THREAD

**Issue by trhinehart-godaddy** [lerna/lerna#4054]
## Current Behavior

When running watch I receive an error:

```bash
 NX   Daemon is not running. The watch command is not supported without the Nx Daemon.
```

Watch cmd
```bash
lerna watch --ignore <api-name> -- lerna run build --stream --scope=%LERNA_PACKAGE_NAME%
```

## Expected Behavior

Run watch apparently needs to init `nx` daemon in latest version.

## Steps to Reproduce

`lerna@8.1.7` with `nx@19.5.3`

Workaround: pin to `nx@19.4.3`

Replated `nx` PR: https://github.com/nrwl/nx/pull/27067

**Comment by kajweb** [comment]
Hey man, have you figured out what's causing this?

**Comment by trhinehart-godaddy** [comment]
> Hey man, have you figured out what's causing this?

there has been several patch versions of `nx` since this issue, I have not tested the latest.

**Comment by greensmith** [comment]
thanks,  your workaround to force nx@19.4.3  worked. 
hopefully someone from nx will look into this at some point

**Comment by susansli** [comment]
Getting the same problem when I try to watch on nx 19.6.0. I am unable to start Nx Daemon at all, every time I run `nx daemon start` it also says "Nx Daemon is not running".

**Comment by NoahAndrews** [comment]
Seeing this on nx 19.6.4 completely out of the blue. It had been working just fine on 19.6.4 previously.

**Comment by NoahAndrews** [comment]
Updating to 19.8.2 did not fix it.

**Comment by NoahAndrews** [comment]
Actual fix: run `nx reset`, which should delete the `.nx/workspace-data/d/disabled` file in your NX workspace.

**Comment by Irupt** [comment]
Hello all, something news about this frustrating bug ?

**Comment by daiscog** [comment]
I kept getting this.  Eventually I noticed that there was a file at `.nx/workspace-data/d/disabled` with the content `true`. 

After deleting this file, the daemon started working as expected again.

**Comment by alantreadway** [comment]
Hi, just hit this error when trying to run the Nx build for `ag-grid/ag-charts` project in Codespaces, when using `nx@20.3.1`.

Looks like when running in a container that you need to explicitly set the `NX_DAEMON=true` environment variable for `nx watch` to pass this check:
https://github.com/nrwl/nx/blob/master/packages/nx/src/daemon/client/client.ts#L127-L165

If `DaemonClient.enabled()` returns `false`, then the `nx watch` command displays the reported message (see https://github.com/nrwl/nx/blob/master/packages/nx/src/command-line/watch/watch.ts#L159-L165) - there are several other checks performed [there](https://github.com/nrwl/nx/blob/master/packages/nx/src/daemon/client/client.ts#L127-L165
), probably worth seeing if your use-case falls into one of these?

**Comment by Ser-Custodio** [comment]
Any news about this ? 
I'm still getting the same error on version 20.6.2.

**Comment by pierluigigiancola** [comment]
thanks @alantreadway I checked the conditions and in my case it was an easy fix. I was missing the nx.json config file at the root of my project

**Comment by toddsmith-adsk** [comment]
I was able to get this working by running the following command

npx nx@latest init

after that was install I no longer got the **nx Daemon is not running.** error when trying to run something like **npx lerna watch -- lerna run build**

Downgrading to 19.4.4 did not help. I'm running on windows.

**Comment by Nokel81** [comment]
This is also a problem when trying to use nx@21

**Comment by heyakyra** [comment]
Possible upstream report: https://github.com/nrwl/nx/issues/28513

I had no `.nx` directory so, while it looked successful, `nx reset` was a noop. 

For some reason, even adding `NX_DAEMON=true` to the script calling `lerna watch` did not make a difference.

But I noticed there is a built-in subcommand `lerna add-caching` which will interactively ask questions and generate a `nx.json` config file: https://lerna.js.org/docs/lerna-and-nx#set-up-1

**Comment by JamesHenry** [comment]
Hi Folks, I just released Lerna v9 that modernized all the dependencies, including Nx as the task runner, and added support for OIDC trusted publishing https://docs.npmjs.com/trusted-publishers, please update to the latest https://github.com/lerna/lerna/releases/tag/v9.0.0

Previously we supported an unsustainably large range of major versions of nx within lerna, leading to unexpected combinations and behaviour. Now that we are focused on the latest and greatest, either:

A) this issue has already been resolved
B) we will be able to create a minimal reproduction that can be patched upstream

Please could some folks update and report back about whether or not it is still reproducible on lerna v9?

Many thanks!

**Comment by theMikeD** [comment]
This seems to have fixed the issue for me: updated to `"lerna": "^9"` and removed the pinned `nx` version and no more drama.

**Comment by heyakyra** [comment]
@JamesHenry commented [last week](https://github.com/lerna/lerna/issues/4054#issuecomment-3323166840):

> Hi Folks, I just released Lerna v9 that modernized all the dependencies, including Nx as the task runner, and added support for OIDC trusted publishing https://docs.npmjs.com/trusted-publishers, please update to the latest https://github.com/lerna/lerna/releases/tag/v9.0.0
> 
> […]
> 
> Please could some folks update and report back about whether or not it is still reproducible on lerna v9?



Hm, after upgrading to v9 and running `lerna repair`, our npm script `NX_DAEMON=true lerna watch -- lerna run build` still fails with ` NX   Daemon is not running. The watch command is not supported without the Nx Daemon.` if there is no `nx.json` file (yes, also ran `npx nx daemon stop --stop`, `npx nx reset`, and even purged the `.nx` directory entirely). 

For reference:

```bash
$ npm list nx
storybook@1.0.0 /var/home/kyra/repos/editshare/storybook
└─┬ lerna@9.0.0
  ├─┬ @lerna/create@9.0.0
  │ └── nx@21.6.2 deduped
  ├─┬ @nx/devkit@21.6.2
  │ └── nx@21.6.2 deduped
  └── nx@21.6.2
```

Any ideas?

**Comment by JamesHenry** [comment]
@heyakyra What do you see if you run: `npx nx daemon`?

**Comment by heyakyra** [comment]
Sidenote, I did look at the source code and I don't see a way that it can work without a conf file: https://github.com/nrwl/nx/issues/28513#issuecomment-3286545039

@JamesHenry commented [yesterday](https://github.com/lerna/lerna/issues/4054#issuecomment-3369031837):
> [@heyakyra](https://github.com/heyakyra) What do you see if you run: `npx nx daemon`?

Initially I get:

```bash
 $ npx nx daemon
Nx Daemon is not running.
```
but
```
$ npx nx daemon --start

 NX   Daemon Server - Started in a background process...

Logs from the Daemon process (ID: 2332147) can be found here: /var/home/kyra/repos/editshare/storybook/node_modules/.cache/nx-workspace-data/d/daemon.log
```
and yet
```
$ NX_DAEMON=true lerna watch --verbose -- npm run lerna:build

lerna notice cli v9.0.0
lerna verb packageConfigs Explicit "packages" configuration found in lerna.json. Resolving packages using the configured glob(s): ["components/*"]
lerna verb rootPath /var/home/kyra/repos/editshare/storybook
lerna info versioning independent
lerna info watch Executing command "npm run lerna:build" on changes in 108 packages.

 NX   Daemon is not running. The watch command is not supported without the Nx Daemon
```

**Comment by JamesHenry** [comment]
Thanks a lot for the digging on that other issue @heyakyra, I've raised it with the team and will get back to you

**Comment by theMikeD** [comment]
I'm now getting the same at @heyakyra 
```
[mike@RA-Replant: /wp-content/] $ npm run watch-impact

> ra@1.0.0 watch-impact
> NODE_ENV=development  npx lerna watch -- lerna run dev --since --scope='@ra/replant-impact'

lerna notice cli v9.0.0
lerna info watch Executing command "lerna run dev --since --scope=@ra/replant-impact" on changes in 6 packages.

 NX   Daemon is not running. The watch command is not supported without the Nx Daemon.

[mike@RA-Replant: /wp-content/] $ npx nx daemon
Nx Daemon is not running.
[mike@RA-Replant: /wp-content/] $ npx nx daemon --start

 NX   Daemon Server - Started in a background process...

Logs from the Daemon process (ID: 95862) can be found here: /Volumes/EVO/Active_Sites/RA/replant_vm/app/public/wp-content/node_modules/.cache/nx-workspace-data/d/daemon.log


[mike@RA-Replant: /wp-content/] $ npm run watch-impact

> ra@1.0.0 watch-impact
> NODE_ENV=development  npx lerna watch -- lerna run dev --since --scope='@ra/replant-impact'

lerna notice cli v9.0.0
lerna info watch Executing command "lerna run dev --since --scope=@ra/replant-impact" on changes in 6 packages.

 NX   Daemon is not running. The watch command is not supported without the Nx Daemon.

[mike@RA-Replant: /wp-content/] $ 
```

```
[NX v21.6.4 Daemon Server] - 2025-10-20T13:42:34.545Z - Started listening on: /private/var/folders/q3/nxdqkgn10qqft8_9p4tqdry4000102/T/187771d2f0e61204d258/d.sock
[NX v21.6.4 Daemon Server] - 2025-10-20T13:42:34.555Z - [WATCHER]: Subscribed to changes within: /Volumes/EVO/Active_Sites/RA/replant_vm/app/public/wp-content (native)
[NX v21.6.4 Daemon Server] - 2025-10-20T13:42:34.557Z - Established a connection. Number of open connections: 1
[NX v21.6.4 Daemon Server] - 2025-10-20T13:42:34.560Z - Closed a connection. Number of open connections: 0
[NX v21.6.4 Daemon Server] - 2025-10-20T13:42:34.663Z - Time taken for 'loadSpecifiedNxPlugins' 1.1197839999999815ms
Time for 'plugin worker 2303 code loading' 3.713757000000001
Time for 'plugin worker 2304 code loading' 3.884802999999998
Time for 'plugin worker 2305 code loading' 3.983235999999998
[NX v21.6.4 Daemon Server] - 2025-10-20T13:42:34.816Z - Time taken for 'Load Nx Plugin: /Volumes/EVO/Active_Sites/RA/replant_vm/app/public/wp-content/node_modules/nx/src/plugins/project-json/build-nodes/project-json' 157.107328ms
[NX v21.6.4 Daemon Server] - 2025-10-20T13:42:34.819Z - Time taken for 'Load Nx Plugin: /Volumes/EVO/Active_Sites/RA/replant_vm/app/public/wp-content/node_modules/nx/src/plugins/package-json' 160.77004800000003ms
[NX v21.6.4 Daemon Server] - 2025-10-20T13:42:34.839Z - [REQUEST]: Updated workspace context based on watched changes, recomputing project graph...
[NX v21.6.4 Daemon Server] - 2025-10-20T13:42:34.843Z - [REQUEST]: 
[NX v21.6.4 Daemon Server] - 2025-10-20T13:42:34.843Z - [REQUEST]: 
Time for 'nx/js/dependencies-and-lockfile:createNodes' 0.4306009999999958
[NX v21.6.4 Daemon Server] - 2025-10-20T13:42:34.854Z - Time taken for 'loadDefaultNxPlugins' 173.582039ms
Time for 'nx/core/project-json:createNodes' 0.13604899999998565
Time for 'nx/core/package-json:createNodes' 8.881236999999999
[NX v21.6.4 Daemon Server] - 2025-10-20T13:42:34.944Z - Time taken for 'build-project-configs' 17.229551000000072ms
Time for 'build typescript dependencies' 0.09606500000001006
[NX v21.6.4 Daemon Server] - 2025-10-20T13:42:35.006Z - Wrote project graph cache to /Volumes/EVO/Active_Sites/RA/replant_vm/app/public/wp-content/node_modules/.cache/nx-workspace-data/project-graph.json
[NX v21.6.4 Daemon Server] - 2025-10-20T13:42:35.006Z - [SYNC]: collect registered sync generators
[NX v21.6.4 Daemon Server] - 2025-10-20T13:42:35.007Z - Time taken for 'total execution time for createProjectGraph()' 60.01117199999999ms
```
