### ISSUE TITLE
import failure: "git diff header lacks filename information when removing 1 leading pathname component"

### ISSUE THREAD

**Issue by ericwooley** [lerna/lerna#432]
I'm trying to init a new lerna instance, and import some (very large) old repo's. And I am running into this error.

```
lerna import ../<some-large-repo>/
Lerna v2.0.0-beta.30
About to import 1947 commits into from ../<some-large-repo>/ into packages/<some-large-repo>
? Are you sure you want to import these commits onto the current branch? Yes
Errored while running ImportCommand.execute
Failed to apply commit a76cb3c23.
Error: Command failed: git am -3
error: git diff header lacks filename information when removing 1 leading pathname component (line 15046)
error: could not build fake ancestor

Rolling back to previous HEAD (commit 3ff03a0).
```

**Comment by gigabo** [comment]
Yikes, that's a new one.  Thanks for reporting @ericwooley.

Is `<some-large-repo>` up on GitHub, by any chance?  Looking for a way to repro this.

**Comment by ericwooley** [comment]
I wish or I would have provided it. Unfortunately its work for a client :(

I am trying to reproduce on something I can open source.

**Comment by ericwooley** [comment]
@gigabo I found that I am having issues with this (which was the original fork)

https://github.com/ericwooley/vortigern

But a different error that simply says, 

```
lerna import ../vortigern/
Lerna v2.0.0-beta.30
About to import 143 commits into from ../vortigern/ into packages/vortigern
? Are you sure you want to import these commits onto the current branch? Yes
Errored while running ImportCommand.execute
Failed to apply commit 518cae8.
Error: Command failed: git am -3
error: Failed to merge in the changes.

Rolling back to previous HEAD (commit 3ff03a0).
```

**Comment by ericwooley** [comment]
I also took a look at the proprietery commit in question from the original import `a76cb3c23`

And it is the addition of 30+ files, with several png's mixed in. Maybe the png files are part of the problem?

**Comment by gigabo** [comment]
Okay, great.  Thanks for tracking down an open repro.

It _looks_ from the error message like there may just be some filenames that we're failing to convert.  The import command does some search-and-replace on patch files produced by `git am`.

**Comment by gigabo** [comment]
Like maybe something similar to https://github.com/lerna/lerna/pull/346, but for _added_ files?

**Comment by ericwooley** [comment]
```
It looks from the error message like there may just be some filenames that we're failing to convert. The import command does some search-and-replace on patch files produced by git am.
```

if I were to git diff a76cb3c23 and a76cb3c23^1 that would be the patch in question right? I'll see if I can find anything funny there

**Comment by ericwooley** [comment]
```
diff --git a/src/app/components/alert/preview/alert.png b/src/app/components/alert/preview/alert.png
deleted file mode 100644
index 1d3fd4e12..000000000
Binary files a/src/app/components/alert/preview/alert.png and /dev/null differ
diff --git a/src/app/components/annotation/annotationComponent.css b/src/app/components/annotation/annotationComponent.css
deleted file mode 100644
index 0fe3a8696..000000000
--- a/src/app/components/annotation/annotationComponent.css
+++ /dev/null
```

here is an excerpt that seems suspicious since there is a bunch of `/dev/null`. stuff happening

**Comment by gigabo** [comment]
Yeah, if you wanted to use the actual command that `import` uses I think it would be:

```
git format-patch -1 a76cb3c23 --stdout
```

**Comment by ericwooley** [comment]
@gigabo Do you have an email or something I can contact you through?

**Comment by gigabo** [comment]
Easiest is probably to jump on [slack](https://slack.lernajs.io/).

**Comment by gigabo** [comment]
Talked with @ericwooley a bit on slack, and it sounds like an _added file_ with a _space in the filename_ may be the culprit here.

In that case the diff looks like:

```
diff --git a/path/too/foo file.png b/path/to/foo file.png
```

My guess is this is tripping up the replacement pattern [here](https://github.com/lerna/lerna/blob/master/src/commands/ImportCommand.js#L97), which looks specifically for non-whitespace in the filename.

**Comment by ericwooley** [comment]
@gigabo figured pointed out that it may have had to do with spaces in the file names, and he is correct.
an example output with a space is: 
```
diff --git a/src/app/some thing.png b/src/app/some thing.png
```

because it searches for the \S+ https://github.com/lerna/lerna/blob/master/src/commands/ImportCommand.js#L97

it breaks on whitespace.

**Comment by ericwooley** [comment]
Looking through https://git-scm.com/docs/git-format-patch documentation, I don't see a way to output in a more parseable manner.

The best possible way to handle this IMO, is to get a list of all files changed in that commit, and look to see if any of them match the last file in the line and use that if so. 

One gotcha to this approach is that you could have `folder/file` and folder `folder/file data/file` which could break the algorithm also. So it would be necessary to check longest file names first and work toward shortest.

If I have time tonight, I'll see if I can do a PR for this.

**Comment by gigabo** [comment]
That sounds like a good approach.  Thanks for taking this on @ericwooley!

**Comment by ericwooley** [comment]
@gigabo 

I implemented my solution in PR https://github.com/lerna/lerna/pull/434

But am running into more problems, and I'm not sure what they are. 

However, I did a little research, and isn't this exactly what git subtree is for? I was able to successfully bring in each repo from the answer here http://stackoverflow.com/questions/6426247/merge-git-repository-in-subdirectory

```
git subtree add -P packages/<my repo> ../<my repo>/ develop
```

**Comment by gigabo** [comment]
Whoa... that move all of the history in to the `packages/<my repo>` path?

How is the commit history attached?  With a merge commit?

That sounds really promising!

**Comment by ericwooley** [comment]
It does retain history, but maybe not as well as the original solution, as files are not listed as `packages/<package>/folder/...` but listed as `folder/...`. 

There is also a giant commit at the HEAD of the repo that adds every file, 

1. blaming the file still seems to work fine everywhere I have looked.

2. logging the file doesn't seem to work.

**Comment by gigabo** [comment]
> logging the file doesn't seem to work.

Oh, hmm... would be nice to preserve this. 😖 

But, on the other hand, we've had [some issues](https://github.com/lerna/lerna/issues/272) with this import strategy for a long time.  A simpler solution that always works might still be better even if it doesn't provide perfect history?

Do you have an idea about what the errors you're still seeing with your PR branch might be?

**Comment by ericwooley** [comment]
I updated the PR to use a better show file command, that allowed me to get through a couple hundred more commits but ran into a new one. But I think this issue will be closed by https://github.com/lerna/lerna/pull/434.

I'll see if I can figure out what is wrong with the next commits.

Patch parsing is aggravating.

**Comment by gigabo** [comment]
> Patch parsing is aggravating.

Yeah, it is. 😞 

Glad you were able to get past _this_ error.  Interested to learn what the _next_ error is.

**Comment by iyobo** [comment]
I think the best thing going forward for lerna is to allow import from actual git repo urls, not a directory. Directories can be interesting.

**Comment by chrisdothtml** [comment]
Sharing my experience since I ran into a brick wall when getting this issue.

The problem does indeed seem to be caused by files/folders in the history that have spaces in them (and has to do with [this line](https://github.com/lerna/lerna/blob/37642a066ed0243d6312240c49c635c3431a989b/commands/import/index.js#L161) only checking for non-whitespace `\S` characters). It seems like a pretty straightforward problem, but doesn't feel like it'd be a straightforward fix.

The way I got around this was by using the [bfg repo cleaner](https://rtyley.github.io/bfg-repo-cleaner/) to delete the offending files/folders (with spaces in them) from the history in my repo. Once I did that, lerna was able to import it successfully

**Comment by evocateur** [comment]
@chrisdothtml Ooh, yeah, that does look likely.

**Comment by chrisdothtml** [comment]
Replacing line 161 with

```
.replace(/^(diff --git (?! b\/).+ b)/gm, replacement)
```

actually covers most scenarios. The only ones it doesn't cover is filepaths containing specifically ' b/' (e.g. `tests/scenario b/...`). All other filespaths with spaces in them are covered, though.

It feels a little hacky, but I can submit a PR for it if you're interested

**Comment by evocateur** [comment]
@chrisdothtml That looks pretty good to me. A PR with a regression test would be great!

(If we wanted to get suuuuuper finicky, we could actually set the [`--src-prefix`](https://git-scm.com/docs/git-diff#git-diff---src-prefixltprefixgt) and [`--dst-prefix`](https://git-scm.com/docs/git-diff#git-diff---dst-prefixltprefixgt) to more ...robust? values, but I think that's an edge case we don't have to worry about right now)
